name: Update Timestamp

on:
  schedule:
    - cron: '*/5 * * * *'  # Adjust to desired interval

jobs:
  update-timestamp:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Update timestamp
        run: echo "Last commit:$(date)" > last-commit.txt

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add last-commit.txt
          git diff --staged --quiet || git commit -m "Update last-commit.txt [skip ci]"
          git push origin HEAD:$(echo $GITHUB_REF | sed -e 's/refs\/heads\///')

#Test
